package com.github.ipecter.rtu.langAPI.enums;

import org.bukkit.Material;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public enum EnumItem {
    NAME_TAG(Material.NAME_TAG, "item.minecraft.name_tag"),
    LEAD(Material.LEAD, "item.minecraft.lead"),
    IRON_SHOVEL(Material.IRON_SHOVEL, "item.minecraft.iron_shovel"),
    IRON_PICKAXE(Material.IRON_PICKAXE, "item.minecraft.iron_pickaxe"),
    IRON_AXE(Material.IRON_AXE, "item.minecraft.iron_axe"),
    FLINT_AND_STEEL(Material.FLINT_AND_STEEL, "item.minecraft.flint_and_steel"),
    APPLE(Material.APPLE, "item.minecraft.apple"),
    COOKIE(Material.COOKIE, "item.minecraft.cookie"),
    BOW(Material.BOW, "item.minecraft.bow"),
    BUNDLE(Material.BUNDLE, "item.minecraft.bundle"),
    //BUNDLE_FULLNESS(Material.BUNDLE_FULLNESS ,"item.minecraft.bundle.fullness"),
    ARROW(Material.ARROW, "item.minecraft.arrow"),
    SPECTRAL_ARROW(Material.SPECTRAL_ARROW, "item.minecraft.spectral_arrow"),
    TIPPED_ARROW(Material.TIPPED_ARROW, "item.minecraft.tipped_arrow"),
    DRIED_KELP(Material.DRIED_KELP, "item.minecraft.dried_kelp"),
    COAL(Material.COAL, "item.minecraft.coal"),
    CHARCOAL(Material.CHARCOAL, "item.minecraft.charcoal"),
    RAW_COPPER(Material.RAW_COPPER, "item.minecraft.raw_copper"),
    RAW_IRON(Material.RAW_IRON, "item.minecraft.raw_iron"),
    RAW_GOLD(Material.RAW_GOLD, "item.minecraft.raw_gold"),
    DIAMOND(Material.DIAMOND, "item.minecraft.diamond"),
    EMERALD(Material.EMERALD, "item.minecraft.emerald"),
    IRON_INGOT(Material.IRON_INGOT, "item.minecraft.iron_ingot"),
    COPPER_INGOT(Material.COPPER_INGOT, "item.minecraft.copper_ingot"),
    GOLD_INGOT(Material.GOLD_INGOT, "item.minecraft.gold_ingot"),
    IRON_SWORD(Material.IRON_SWORD, "item.minecraft.iron_sword"),
    WOODEN_SWORD(Material.WOODEN_SWORD, "item.minecraft.wooden_sword"),
    WOODEN_SHOVEL(Material.WOODEN_SHOVEL, "item.minecraft.wooden_shovel"),
    WOODEN_PICKAXE(Material.WOODEN_PICKAXE, "item.minecraft.wooden_pickaxe"),
    WOODEN_AXE(Material.WOODEN_AXE, "item.minecraft.wooden_axe"),
    STONE_SWORD(Material.STONE_SWORD, "item.minecraft.stone_sword"),
    STONE_SHOVEL(Material.STONE_SHOVEL, "item.minecraft.stone_shovel"),
    STONE_PICKAXE(Material.STONE_PICKAXE, "item.minecraft.stone_pickaxe"),
    STONE_AXE(Material.STONE_AXE, "item.minecraft.stone_axe"),
    DIAMOND_SWORD(Material.DIAMOND_SWORD, "item.minecraft.diamond_sword"),
    DIAMOND_SHOVEL(Material.DIAMOND_SHOVEL, "item.minecraft.diamond_shovel"),
    DIAMOND_PICKAXE(Material.DIAMOND_PICKAXE, "item.minecraft.diamond_pickaxe"),
    DIAMOND_AXE(Material.DIAMOND_AXE, "item.minecraft.diamond_axe"),
    STICK(Material.STICK, "item.minecraft.stick"),
    BOWL(Material.BOWL, "item.minecraft.bowl"),
    MUSHROOM_STEW(Material.MUSHROOM_STEW, "item.minecraft.mushroom_stew"),
    GOLDEN_SWORD(Material.GOLDEN_SWORD, "item.minecraft.golden_sword"),
    GOLDEN_SHOVEL(Material.GOLDEN_SHOVEL, "item.minecraft.golden_shovel"),
    GOLDEN_PICKAXE(Material.GOLDEN_PICKAXE, "item.minecraft.golden_pickaxe"),
    GOLDEN_AXE(Material.GOLDEN_AXE, "item.minecraft.golden_axe"),
    STRING(Material.STRING, "item.minecraft.string"),
    FEATHER(Material.FEATHER, "item.minecraft.feather"),
    GUNPOWDER(Material.GUNPOWDER, "item.minecraft.gunpowder"),
    WOODEN_HOE(Material.WOODEN_HOE, "item.minecraft.wooden_hoe"),
    STONE_HOE(Material.STONE_HOE, "item.minecraft.stone_hoe"),
    IRON_HOE(Material.IRON_HOE, "item.minecraft.iron_hoe"),
    DIAMOND_HOE(Material.DIAMOND_HOE, "item.minecraft.diamond_hoe"),
    GOLDEN_HOE(Material.GOLDEN_HOE, "item.minecraft.golden_hoe"),
    WHEAT_SEEDS(Material.WHEAT_SEEDS, "item.minecraft.wheat_seeds"),
    PUMPKIN_SEEDS(Material.PUMPKIN_SEEDS, "item.minecraft.pumpkin_seeds"),
    MELON_SEEDS(Material.MELON_SEEDS, "item.minecraft.melon_seeds"),
    MELON_SLICE(Material.MELON_SLICE, "item.minecraft.melon_slice"),
    WHEAT(Material.WHEAT, "item.minecraft.wheat"),
    BREAD(Material.BREAD, "item.minecraft.bread"),
    LEATHER_HELMET(Material.LEATHER_HELMET, "item.minecraft.leather_helmet"),
    LEATHER_CHESTPLATE(Material.LEATHER_CHESTPLATE, "item.minecraft.leather_chestplate"),
    LEATHER_LEGGINGS(Material.LEATHER_LEGGINGS, "item.minecraft.leather_leggings"),
    LEATHER_BOOTS(Material.LEATHER_BOOTS, "item.minecraft.leather_boots"),
    CHAINMAIL_HELMET(Material.CHAINMAIL_HELMET, "item.minecraft.chainmail_helmet"),
    CHAINMAIL_CHESTPLATE(Material.CHAINMAIL_CHESTPLATE, "item.minecraft.chainmail_chestplate"),
    CHAINMAIL_LEGGINGS(Material.CHAINMAIL_LEGGINGS, "item.minecraft.chainmail_leggings"),
    CHAINMAIL_BOOTS(Material.CHAINMAIL_BOOTS, "item.minecraft.chainmail_boots"),
    IRON_HELMET(Material.IRON_HELMET, "item.minecraft.iron_helmet"),
    IRON_CHESTPLATE(Material.IRON_CHESTPLATE, "item.minecraft.iron_chestplate"),
    IRON_LEGGINGS(Material.IRON_LEGGINGS, "item.minecraft.iron_leggings"),
    IRON_BOOTS(Material.IRON_BOOTS, "item.minecraft.iron_boots"),
    DIAMOND_HELMET(Material.DIAMOND_HELMET, "item.minecraft.diamond_helmet"),
    DIAMOND_CHESTPLATE(Material.DIAMOND_CHESTPLATE, "item.minecraft.diamond_chestplate"),
    DIAMOND_LEGGINGS(Material.DIAMOND_LEGGINGS, "item.minecraft.diamond_leggings"),
    DIAMOND_BOOTS(Material.DIAMOND_BOOTS, "item.minecraft.diamond_boots"),
    GOLDEN_HELMET(Material.GOLDEN_HELMET, "item.minecraft.golden_helmet"),
    GOLDEN_CHESTPLATE(Material.GOLDEN_CHESTPLATE, "item.minecraft.golden_chestplate"),
    GOLDEN_LEGGINGS(Material.GOLDEN_LEGGINGS, "item.minecraft.golden_leggings"),
    GOLDEN_BOOTS(Material.GOLDEN_BOOTS, "item.minecraft.golden_boots"),
    FLINT(Material.FLINT, "item.minecraft.flint"),
    PORKCHOP(Material.PORKCHOP, "item.minecraft.porkchop"),
    COOKED_PORKCHOP(Material.COOKED_PORKCHOP, "item.minecraft.cooked_porkchop"),
    CHICKEN(Material.CHICKEN, "item.minecraft.chicken"),
    COOKED_CHICKEN(Material.COOKED_CHICKEN, "item.minecraft.cooked_chicken"),
    MUTTON(Material.MUTTON, "item.minecraft.mutton"),
    COOKED_MUTTON(Material.COOKED_MUTTON, "item.minecraft.cooked_mutton"),
    RABBIT(Material.RABBIT, "item.minecraft.rabbit"),
    COOKED_RABBIT(Material.COOKED_RABBIT, "item.minecraft.cooked_rabbit"),
    RABBIT_STEW(Material.RABBIT_STEW, "item.minecraft.rabbit_stew"),
    RABBIT_FOOT(Material.RABBIT_FOOT, "item.minecraft.rabbit_foot"),
    RABBIT_HIDE(Material.RABBIT_HIDE, "item.minecraft.rabbit_hide"),
    BEEF(Material.BEEF, "item.minecraft.beef"),
    COOKED_BEEF(Material.COOKED_BEEF, "item.minecraft.cooked_beef"),
    PAINTING(Material.PAINTING, "item.minecraft.painting"),
    ITEM_FRAME(Material.ITEM_FRAME, "item.minecraft.item_frame"),
    GOLDEN_APPLE(Material.GOLDEN_APPLE, "item.minecraft.golden_apple"),
    ENCHANTED_GOLDEN_APPLE(Material.ENCHANTED_GOLDEN_APPLE, "item.minecraft.enchanted_golden_apple"),
    OAK_SIGN(Material.OAK_SIGN ,"block.minecraft.oak_sign"),
    SPRUCE_SIGN(Material.SPRUCE_SIGN ,"block.minecraft.spruce_sign"),
    BIRCH_SIGN(Material.BIRCH_SIGN ,"block.minecraft.birch_sign"),
    ACACIA_SIGN(Material.ACACIA_SIGN ,"block.minecraft.acacia_sign"),
    JUNGLE_SIGN(Material.JUNGLE_SIGN ,"block.minecraft.jungle_sign"),
    DARK_OAK_SIGN(Material.DARK_OAK_SIGN ,"block.minecraft.dark_oak_sign"),
    BUCKET(Material.BUCKET, "item.minecraft.bucket"),
    WATER_BUCKET(Material.WATER_BUCKET, "item.minecraft.water_bucket"),
    LAVA_BUCKET(Material.LAVA_BUCKET, "item.minecraft.lava_bucket"),
    PUFFERFISH_BUCKET(Material.PUFFERFISH_BUCKET, "item.minecraft.pufferfish_bucket"),
    SALMON_BUCKET(Material.SALMON_BUCKET, "item.minecraft.salmon_bucket"),
    COD_BUCKET(Material.COD_BUCKET, "item.minecraft.cod_bucket"),
    TROPICAL_FISH_BUCKET(Material.TROPICAL_FISH_BUCKET, "item.minecraft.tropical_fish_bucket"),
    POWDER_SNOW_BUCKET(Material.POWDER_SNOW_BUCKET, "item.minecraft.powder_snow_bucket"),
    AXOLOTL_BUCKET(Material.AXOLOTL_BUCKET, "item.minecraft.axolotl_bucket"),
    MINECART(Material.MINECART, "item.minecraft.minecart"),
    SADDLE(Material.SADDLE, "item.minecraft.saddle"),
    REDSTONE(Material.REDSTONE, "item.minecraft.redstone"),
    SNOWBALL(Material.SNOWBALL, "item.minecraft.snowball"),
    OAK_BOAT(Material.OAK_BOAT, "item.minecraft.oak_boat"),
    SPRUCE_BOAT(Material.SPRUCE_BOAT, "item.minecraft.spruce_boat"),
    BIRCH_BOAT(Material.BIRCH_BOAT, "item.minecraft.birch_boat"),
    JUNGLE_BOAT(Material.JUNGLE_BOAT, "item.minecraft.jungle_boat"),
    ACACIA_BOAT(Material.ACACIA_BOAT, "item.minecraft.acacia_boat"),
    DARK_OAK_BOAT(Material.DARK_OAK_BOAT, "item.minecraft.dark_oak_boat"),
    LEATHER(Material.LEATHER, "item.minecraft.leather"),
    MILK_BUCKET(Material.MILK_BUCKET, "item.minecraft.milk_bucket"),
    BRICK(Material.BRICK, "item.minecraft.brick"),
    CLAY_BALL(Material.CLAY_BALL, "item.minecraft.clay_ball"),
    PAPER(Material.PAPER, "item.minecraft.paper"),
    BOOK(Material.BOOK, "item.minecraft.book"),
    SLIME_BALL(Material.SLIME_BALL, "item.minecraft.slime_ball"),
    CHEST_MINECART(Material.CHEST_MINECART, "item.minecraft.chest_minecart"),
    FURNACE_MINECART(Material.FURNACE_MINECART, "item.minecraft.furnace_minecart"),
    TNT_MINECART(Material.TNT_MINECART, "item.minecraft.tnt_minecart"),
    HOPPER_MINECART(Material.HOPPER_MINECART, "item.minecraft.hopper_minecart"),
    COMMAND_BLOCK_MINECART(Material.COMMAND_BLOCK_MINECART, "item.minecraft.command_block_minecart"),
    EGG(Material.EGG, "item.minecraft.egg"),
    COMPASS(Material.COMPASS, "item.minecraft.compass"),
    FISHING_ROD(Material.FISHING_ROD, "item.minecraft.fishing_rod"),
    CLOCK(Material.CLOCK, "item.minecraft.clock"),
    GLOWSTONE_DUST(Material.GLOWSTONE_DUST, "item.minecraft.glowstone_dust"),
    COD(Material.COD, "item.minecraft.cod"),
    SALMON(Material.SALMON, "item.minecraft.salmon"),
    PUFFERFISH(Material.PUFFERFISH, "item.minecraft.pufferfish"),
    TROPICAL_FISH(Material.TROPICAL_FISH, "item.minecraft.tropical_fish"),
    COOKED_COD(Material.COOKED_COD, "item.minecraft.cooked_cod"),
    COOKED_SALMON(Material.COOKED_SALMON, "item.minecraft.cooked_salmon"),
    MUSIC_DISC_13(Material.MUSIC_DISC_13, "item.minecraft.music_disc_13"),
    MUSIC_DISC_CAT(Material.MUSIC_DISC_CAT, "item.minecraft.music_disc_cat"),
    MUSIC_DISC_BLOCKS(Material.MUSIC_DISC_BLOCKS, "item.minecraft.music_disc_blocks"),
    MUSIC_DISC_CHIRP(Material.MUSIC_DISC_CHIRP, "item.minecraft.music_disc_chirp"),
    MUSIC_DISC_FAR(Material.MUSIC_DISC_FAR, "item.minecraft.music_disc_far"),
    MUSIC_DISC_MALL(Material.MUSIC_DISC_MALL, "item.minecraft.music_disc_mall"),
    MUSIC_DISC_MELLOHI(Material.MUSIC_DISC_MELLOHI, "item.minecraft.music_disc_mellohi"),
    MUSIC_DISC_STAL(Material.MUSIC_DISC_STAL, "item.minecraft.music_disc_stal"),
    MUSIC_DISC_STRAD(Material.MUSIC_DISC_STRAD, "item.minecraft.music_disc_strad"),
    MUSIC_DISC_WARD(Material.MUSIC_DISC_WARD, "item.minecraft.music_disc_ward"),
    MUSIC_DISC_11(Material.MUSIC_DISC_11, "item.minecraft.music_disc_11"),
    MUSIC_DISC_WAIT(Material.MUSIC_DISC_WAIT, "item.minecraft.music_disc_wait"),
    MUSIC_DISC_PIGSTEP(Material.MUSIC_DISC_PIGSTEP, "item.minecraft.music_disc_pigstep"),
    MUSIC_DISC_OTHERSIDE(Material.MUSIC_DISC_OTHERSIDE, "item.minecraft.music_disc_otherside"),
    //    MUSIC_DISC_13_DESC(Material.MUSIC_DISC_13_DESC ,"item.minecraft.music_disc_13.desc"),
//    MUSIC_DISC_CAT_DESC(Material.MUSIC_DISC_CAT_DESC ,"item.minecraft.music_disc_cat.desc"),
//    MUSIC_DISC_BLOCKS_DESC(Material.MUSIC_DISC_BLOCKS_DESC ,"item.minecraft.music_disc_blocks.desc"),
//    MUSIC_DISC_CHIRP_DESC(Material.MUSIC_DISC_CHIRP_DESC ,"item.minecraft.music_disc_chirp.desc"),
//    MUSIC_DISC_FAR_DESC(Material.MUSIC_DISC_FAR_DESC ,"item.minecraft.music_disc_far.desc"),
//    MUSIC_DISC_MALL_DESC(Material.MUSIC_DISC_MALL_DESC ,"item.minecraft.music_disc_mall.desc"),
//    MUSIC_DISC_MELLOHI_DESC(Material.MUSIC_DISC_MELLOHI_DESC ,"item.minecraft.music_disc_mellohi.desc"),
//    MUSIC_DISC_STAL_DESC(Material.MUSIC_DISC_STAL_DESC ,"item.minecraft.music_disc_stal.desc"),
//    MUSIC_DISC_STRAD_DESC(Material.MUSIC_DISC_STRAD_DESC ,"item.minecraft.music_disc_strad.desc"),
//    MUSIC_DISC_WARD_DESC(Material.MUSIC_DISC_WARD_DESC ,"item.minecraft.music_disc_ward.desc"),
//    MUSIC_DISC_11_DESC(Material.MUSIC_DISC_11_DESC ,"item.minecraft.music_disc_11.desc"),
//    MUSIC_DISC_WAIT_DESC(Material.MUSIC_DISC_WAIT_DESC ,"item.minecraft.music_disc_wait.desc"),
//    MUSIC_DISC_PIGSTEP_DESC(Material.MUSIC_DISC_PIGSTEP_DESC ,"item.minecraft.music_disc_pigstep.desc"),
//    MUSIC_DISC_OTHERSIDE_DESC(Material.MUSIC_DISC_OTHERSIDE_DESC ,"item.minecraft.music_disc_otherside.desc"),
    BONE(Material.BONE, "item.minecraft.bone"),
    INK_SAC(Material.INK_SAC, "item.minecraft.ink_sac"),
    RED_DYE(Material.RED_DYE, "item.minecraft.red_dye"),
    GREEN_DYE(Material.GREEN_DYE, "item.minecraft.green_dye"),
    COCOA_BEANS(Material.COCOA_BEANS, "item.minecraft.cocoa_beans"),
    LAPIS_LAZULI(Material.LAPIS_LAZULI, "item.minecraft.lapis_lazuli"),
    PURPLE_DYE(Material.PURPLE_DYE, "item.minecraft.purple_dye"),
    CYAN_DYE(Material.CYAN_DYE, "item.minecraft.cyan_dye"),
    LIGHT_GRAY_DYE(Material.LIGHT_GRAY_DYE, "item.minecraft.light_gray_dye"),
    GRAY_DYE(Material.GRAY_DYE, "item.minecraft.gray_dye"),
    PINK_DYE(Material.PINK_DYE, "item.minecraft.pink_dye"),
    LIME_DYE(Material.LIME_DYE, "item.minecraft.lime_dye"),
    YELLOW_DYE(Material.YELLOW_DYE, "item.minecraft.yellow_dye"),
    LIGHT_BLUE_DYE(Material.LIGHT_BLUE_DYE, "item.minecraft.light_blue_dye"),
    MAGENTA_DYE(Material.MAGENTA_DYE, "item.minecraft.magenta_dye"),
    ORANGE_DYE(Material.ORANGE_DYE, "item.minecraft.orange_dye"),
    BONE_MEAL(Material.BONE_MEAL, "item.minecraft.bone_meal"),
    BLUE_DYE(Material.BLUE_DYE, "item.minecraft.blue_dye"),
    BLACK_DYE(Material.BLACK_DYE, "item.minecraft.black_dye"),
    BROWN_DYE(Material.BROWN_DYE, "item.minecraft.brown_dye"),
    WHITE_DYE(Material.WHITE_DYE, "item.minecraft.white_dye"),
    SUGAR(Material.SUGAR, "item.minecraft.sugar"),
    AMETHYST_SHARD(Material.AMETHYST_SHARD, "item.minecraft.amethyst_shard"),
    SPYGLASS(Material.SPYGLASS, "item.minecraft.spyglass"),
    GLOW_BERRIES(Material.GLOW_BERRIES, "item.minecraft.glow_berries"),
    FILLED_MAP(Material.FILLED_MAP, "item.minecraft.filled_map"),
    SHEARS(Material.SHEARS, "item.minecraft.shears"),
    ROTTEN_FLESH(Material.ROTTEN_FLESH, "item.minecraft.rotten_flesh"),
    ENDER_PEARL(Material.ENDER_PEARL, "item.minecraft.ender_pearl"),
    BLAZE_ROD(Material.BLAZE_ROD, "item.minecraft.blaze_rod"),
    GHAST_TEAR(Material.GHAST_TEAR, "item.minecraft.ghast_tear"),
    NETHER_WART(Material.NETHER_WART, "item.minecraft.nether_wart"),
    POTION(Material.POTION, "item.minecraft.potion"),
    SPLASH_POTION(Material.SPLASH_POTION, "item.minecraft.splash_potion"),
    LINGERING_POTION(Material.LINGERING_POTION, "item.minecraft.lingering_potion"),
    END_CRYSTAL(Material.END_CRYSTAL, "item.minecraft.end_crystal"),
    GOLD_NUGGET(Material.GOLD_NUGGET, "item.minecraft.gold_nugget"),
    GLASS_BOTTLE(Material.GLASS_BOTTLE, "item.minecraft.glass_bottle"),
    SPIDER_EYE(Material.SPIDER_EYE, "item.minecraft.spider_eye"),
    FERMENTED_SPIDER_EYE(Material.FERMENTED_SPIDER_EYE, "item.minecraft.fermented_spider_eye"),
    BLAZE_POWDER(Material.BLAZE_POWDER, "item.minecraft.blaze_powder"),
    MAGMA_CREAM(Material.MAGMA_CREAM, "item.minecraft.magma_cream"),
    CAULDRON(Material.CAULDRON, "item.minecraft.cauldron"),
    BREWING_STAND(Material.BREWING_STAND, "item.minecraft.brewing_stand"),
    ENDER_EYE(Material.ENDER_EYE, "item.minecraft.ender_eye"),
    GLISTERING_MELON_SLICE(Material.GLISTERING_MELON_SLICE, "item.minecraft.glistering_melon_slice"),
    AXOLOTL_SPAWN_EGG(Material.AXOLOTL_SPAWN_EGG, "item.minecraft.axolotl_spawn_egg"),
    BAT_SPAWN_EGG(Material.BAT_SPAWN_EGG, "item.minecraft.bat_spawn_egg"),
    BEE_SPAWN_EGG(Material.BEE_SPAWN_EGG, "item.minecraft.bee_spawn_egg"),
    BLAZE_SPAWN_EGG(Material.BLAZE_SPAWN_EGG, "item.minecraft.blaze_spawn_egg"),
    CAT_SPAWN_EGG(Material.CAT_SPAWN_EGG, "item.minecraft.cat_spawn_egg"),
    CAVE_SPIDER_SPAWN_EGG(Material.CAVE_SPIDER_SPAWN_EGG, "item.minecraft.cave_spider_spawn_egg"),
    CHICKEN_SPAWN_EGG(Material.CHICKEN_SPAWN_EGG, "item.minecraft.chicken_spawn_egg"),
    COD_SPAWN_EGG(Material.COD_SPAWN_EGG, "item.minecraft.cod_spawn_egg"),
    COW_SPAWN_EGG(Material.COW_SPAWN_EGG, "item.minecraft.cow_spawn_egg"),
    CREEPER_SPAWN_EGG(Material.CREEPER_SPAWN_EGG, "item.minecraft.creeper_spawn_egg"),
    DOLPHIN_SPAWN_EGG(Material.DOLPHIN_SPAWN_EGG, "item.minecraft.dolphin_spawn_egg"),
    DONKEY_SPAWN_EGG(Material.DONKEY_SPAWN_EGG, "item.minecraft.donkey_spawn_egg"),
    DROWNED_SPAWN_EGG(Material.DROWNED_SPAWN_EGG, "item.minecraft.drowned_spawn_egg"),
    ELDER_GUARDIAN_SPAWN_EGG(Material.ELDER_GUARDIAN_SPAWN_EGG, "item.minecraft.elder_guardian_spawn_egg"),
    ENDERMAN_SPAWN_EGG(Material.ENDERMAN_SPAWN_EGG, "item.minecraft.enderman_spawn_egg"),
    ENDERMITE_SPAWN_EGG(Material.ENDERMITE_SPAWN_EGG, "item.minecraft.endermite_spawn_egg"),
    EVOKER_SPAWN_EGG(Material.EVOKER_SPAWN_EGG, "item.minecraft.evoker_spawn_egg"),
    GHAST_SPAWN_EGG(Material.GHAST_SPAWN_EGG, "item.minecraft.ghast_spawn_egg"),
    GLOW_SQUID_SPAWN_EGG(Material.GLOW_SQUID_SPAWN_EGG, "item.minecraft.glow_squid_spawn_egg"),
    GUARDIAN_SPAWN_EGG(Material.GUARDIAN_SPAWN_EGG, "item.minecraft.guardian_spawn_egg"),
    HOGLIN_SPAWN_EGG(Material.HOGLIN_SPAWN_EGG, "item.minecraft.hoglin_spawn_egg"),
    HORSE_SPAWN_EGG(Material.HORSE_SPAWN_EGG, "item.minecraft.horse_spawn_egg"),
    HUSK_SPAWN_EGG(Material.HUSK_SPAWN_EGG, "item.minecraft.husk_spawn_egg"),
    RAVAGER_SPAWN_EGG(Material.RAVAGER_SPAWN_EGG, "item.minecraft.ravager_spawn_egg"),
    LLAMA_SPAWN_EGG(Material.LLAMA_SPAWN_EGG, "item.minecraft.llama_spawn_egg"),
    MAGMA_CUBE_SPAWN_EGG(Material.MAGMA_CUBE_SPAWN_EGG, "item.minecraft.magma_cube_spawn_egg"),
    MOOSHROOM_SPAWN_EGG(Material.MOOSHROOM_SPAWN_EGG, "item.minecraft.mooshroom_spawn_egg"),
    MULE_SPAWN_EGG(Material.MULE_SPAWN_EGG, "item.minecraft.mule_spawn_egg"),
    OCELOT_SPAWN_EGG(Material.OCELOT_SPAWN_EGG, "item.minecraft.ocelot_spawn_egg"),
    PANDA_SPAWN_EGG(Material.PANDA_SPAWN_EGG, "item.minecraft.panda_spawn_egg"),
    PARROT_SPAWN_EGG(Material.PARROT_SPAWN_EGG, "item.minecraft.parrot_spawn_egg"),
    PIG_SPAWN_EGG(Material.PIG_SPAWN_EGG, "item.minecraft.pig_spawn_egg"),
    PIGLIN_SPAWN_EGG(Material.PIGLIN_SPAWN_EGG, "item.minecraft.piglin_spawn_egg"),
    PIGLIN_BRUTE_SPAWN_EGG(Material.PIGLIN_BRUTE_SPAWN_EGG, "item.minecraft.piglin_brute_spawn_egg"),
    PILLAGER_SPAWN_EGG(Material.PILLAGER_SPAWN_EGG, "item.minecraft.pillager_spawn_egg"),
    PHANTOM_SPAWN_EGG(Material.PHANTOM_SPAWN_EGG, "item.minecraft.phantom_spawn_egg"),
    POLAR_BEAR_SPAWN_EGG(Material.POLAR_BEAR_SPAWN_EGG, "item.minecraft.polar_bear_spawn_egg"),
    PUFFERFISH_SPAWN_EGG(Material.PUFFERFISH_SPAWN_EGG, "item.minecraft.pufferfish_spawn_egg"),
    RABBIT_SPAWN_EGG(Material.RABBIT_SPAWN_EGG, "item.minecraft.rabbit_spawn_egg"),
    FOX_SPAWN_EGG(Material.FOX_SPAWN_EGG, "item.minecraft.fox_spawn_egg"),
    SALMON_SPAWN_EGG(Material.SALMON_SPAWN_EGG, "item.minecraft.salmon_spawn_egg"),
    SHEEP_SPAWN_EGG(Material.SHEEP_SPAWN_EGG, "item.minecraft.sheep_spawn_egg"),
    SHULKER_SPAWN_EGG(Material.SHULKER_SPAWN_EGG, "item.minecraft.shulker_spawn_egg"),
    SILVERFISH_SPAWN_EGG(Material.SILVERFISH_SPAWN_EGG, "item.minecraft.silverfish_spawn_egg"),
    SKELETON_SPAWN_EGG(Material.SKELETON_SPAWN_EGG, "item.minecraft.skeleton_spawn_egg"),
    SKELETON_HORSE_SPAWN_EGG(Material.SKELETON_HORSE_SPAWN_EGG, "item.minecraft.skeleton_horse_spawn_egg"),
    SLIME_SPAWN_EGG(Material.SLIME_SPAWN_EGG, "item.minecraft.slime_spawn_egg"),
    SPIDER_SPAWN_EGG(Material.SPIDER_SPAWN_EGG, "item.minecraft.spider_spawn_egg"),
    SQUID_SPAWN_EGG(Material.SQUID_SPAWN_EGG, "item.minecraft.squid_spawn_egg"),
    STRAY_SPAWN_EGG(Material.STRAY_SPAWN_EGG, "item.minecraft.stray_spawn_egg"),
    STRIDER_SPAWN_EGG(Material.STRIDER_SPAWN_EGG, "item.minecraft.strider_spawn_egg"),
    TRADER_LLAMA_SPAWN_EGG(Material.TRADER_LLAMA_SPAWN_EGG, "item.minecraft.trader_llama_spawn_egg"),
    TROPICAL_FISH_SPAWN_EGG(Material.TROPICAL_FISH_SPAWN_EGG, "item.minecraft.tropical_fish_spawn_egg"),
    TURTLE_SPAWN_EGG(Material.TURTLE_SPAWN_EGG, "item.minecraft.turtle_spawn_egg"),
    VEX_SPAWN_EGG(Material.VEX_SPAWN_EGG, "item.minecraft.vex_spawn_egg"),
    VILLAGER_SPAWN_EGG(Material.VILLAGER_SPAWN_EGG, "item.minecraft.villager_spawn_egg"),
    WANDERING_TRADER_SPAWN_EGG(Material.WANDERING_TRADER_SPAWN_EGG, "item.minecraft.wandering_trader_spawn_egg"),
    VINDICATOR_SPAWN_EGG(Material.VINDICATOR_SPAWN_EGG, "item.minecraft.vindicator_spawn_egg"),
    WITCH_SPAWN_EGG(Material.WITCH_SPAWN_EGG, "item.minecraft.witch_spawn_egg"),
    WITHER_SKELETON_SPAWN_EGG(Material.WITHER_SKELETON_SPAWN_EGG, "item.minecraft.wither_skeleton_spawn_egg"),
    WOLF_SPAWN_EGG(Material.WOLF_SPAWN_EGG, "item.minecraft.wolf_spawn_egg"),
    ZOGLIN_SPAWN_EGG(Material.ZOGLIN_SPAWN_EGG, "item.minecraft.zoglin_spawn_egg"),
    ZOMBIE_SPAWN_EGG(Material.ZOMBIE_SPAWN_EGG, "item.minecraft.zombie_spawn_egg"),
    ZOMBIE_HORSE_SPAWN_EGG(Material.ZOMBIE_HORSE_SPAWN_EGG, "item.minecraft.zombie_horse_spawn_egg"),
    ZOMBIFIED_PIGLIN_SPAWN_EGG(Material.ZOMBIFIED_PIGLIN_SPAWN_EGG, "item.minecraft.zombified_piglin_spawn_egg"),
    ZOMBIE_VILLAGER_SPAWN_EGG(Material.ZOMBIE_VILLAGER_SPAWN_EGG, "item.minecraft.zombie_villager_spawn_egg"),
    GOAT_SPAWN_EGG(Material.GOAT_SPAWN_EGG, "item.minecraft.goat_spawn_egg"),
    EXPERIENCE_BOTTLE(Material.EXPERIENCE_BOTTLE, "item.minecraft.experience_bottle"),
    FIRE_CHARGE(Material.FIRE_CHARGE, "item.minecraft.fire_charge"),
    WRITABLE_BOOK(Material.WRITABLE_BOOK, "item.minecraft.writable_book"),
    WRITTEN_BOOK(Material.WRITTEN_BOOK, "item.minecraft.written_book"),
    FLOWER_POT(Material.FLOWER_POT, "item.minecraft.flower_pot"),
    MAP(Material.MAP, "item.minecraft.map"),
    CARROT(Material.CARROT, "item.minecraft.carrot"),
    GOLDEN_CARROT(Material.GOLDEN_CARROT, "item.minecraft.golden_carrot"),
    POTATO(Material.POTATO, "item.minecraft.potato"),
    BAKED_POTATO(Material.BAKED_POTATO, "item.minecraft.baked_potato"),
    POISONOUS_POTATO(Material.POISONOUS_POTATO, "item.minecraft.poisonous_potato"),
    CARROT_ON_A_STICK(Material.CARROT_ON_A_STICK, "item.minecraft.carrot_on_a_stick"),
    NETHER_STAR(Material.NETHER_STAR, "item.minecraft.nether_star"),
    PUMPKIN_PIE(Material.PUMPKIN_PIE, "item.minecraft.pumpkin_pie"),
    ENCHANTED_BOOK(Material.ENCHANTED_BOOK, "item.minecraft.enchanted_book"),
    FIREWORK_ROCKET(Material.FIREWORK_ROCKET, "item.minecraft.firework_rocket"),
    //FIREWORK_ROCKET_FLIGHT(Material.FIREWORK_ROCKET_FLIGHT ,"item.minecraft.firework_rocket.flight"),
    FIREWORK_STAR(Material.FIREWORK_STAR, "item.minecraft.firework_star"),
    //    FIREWORK_STAR_BLACK(Material.FIREWORK_STAR_BLACK ,"item.minecraft.firework_star.black"),
//    FIREWORK_STAR_RED(Material.FIREWORK_STAR_RED ,"item.minecraft.firework_star.red"),
//    FIREWORK_STAR_GREEN(Material.FIREWORK_STAR_GREEN ,"item.minecraft.firework_star.green"),
//    FIREWORK_STAR_BROWN(Material.FIREWORK_STAR_BROWN ,"item.minecraft.firework_star.brown"),
//    FIREWORK_STAR_BLUE(Material.FIREWORK_STAR_BLUE ,"item.minecraft.firework_star.blue"),
//    FIREWORK_STAR_PURPLE(Material.FIREWORK_STAR_PURPLE ,"item.minecraft.firework_star.purple"),
//    FIREWORK_STAR_CYAN(Material.FIREWORK_STAR_CYAN ,"item.minecraft.firework_star.cyan"),
//    FIREWORK_STAR_LIGHT_GRAY(Material.FIREWORK_STAR_LIGHT_GRAY ,"item.minecraft.firework_star.light_gray"),
//    FIREWORK_STAR_GRAY(Material.FIREWORK_STAR_GRAY ,"item.minecraft.firework_star.gray"),
//    FIREWORK_STAR_PINK(Material.FIREWORK_STAR_PINK ,"item.minecraft.firework_star.pink"),
//    FIREWORK_STAR_LIME(Material.FIREWORK_STAR_LIME ,"item.minecraft.firework_star.lime"),
//    FIREWORK_STAR_YELLOW(Material.FIREWORK_STAR_YELLOW ,"item.minecraft.firework_star.yellow"),
//    FIREWORK_STAR_LIGHT_BLUE(Material.FIREWORK_STAR_LIGHT_BLUE ,"item.minecraft.firework_star.light_blue"),
//    FIREWORK_STAR_MAGENTA(Material.FIREWORK_STAR_MAGENTA ,"item.minecraft.firework_star.magenta"),
//    FIREWORK_STAR_ORANGE(Material.FIREWORK_STAR_ORANGE ,"item.minecraft.firework_star.orange"),
//    FIREWORK_STAR_WHITE(Material.FIREWORK_STAR_WHITE ,"item.minecraft.firework_star.white"),
//    FIREWORK_STAR_CUSTOM_COLOR(Material.FIREWORK_STAR_CUSTOM_COLOR ,"item.minecraft.firework_star.custom_color"),
//    FIREWORK_STAR_FADE_TO(Material.FIREWORK_STAR_FADE_TO ,"item.minecraft.firework_star.fade_to"),
//    FIREWORK_STAR_FLICKER(Material.FIREWORK_STAR_FLICKER ,"item.minecraft.firework_star.flicker"),
//    FIREWORK_STAR_TRAIL(Material.FIREWORK_STAR_TRAIL ,"item.minecraft.firework_star.trail"),
//    FIREWORK_STAR_SHAPE_SMALL_BALL(Material.FIREWORK_STAR_SHAPE_SMALL_BALL ,"item.minecraft.firework_star.shape.small_ball"),
//    FIREWORK_STAR_SHAPE_LARGE_BALL(Material.FIREWORK_STAR_SHAPE_LARGE_BALL ,"item.minecraft.firework_star.shape.large_ball"),
//    FIREWORK_STAR_SHAPE_STAR(Material.FIREWORK_STAR_SHAPE_STAR ,"item.minecraft.firework_star.shape.star"),
//    FIREWORK_STAR_SHAPE_CREEPER(Material.FIREWORK_STAR_SHAPE_CREEPER ,"item.minecraft.firework_star.shape.creeper"),
//    FIREWORK_STAR_SHAPE_BURST(Material.FIREWORK_STAR_SHAPE_BURST ,"item.minecraft.firework_star.shape.burst"),
//    FIREWORK_STAR_SHAPE(Material.FIREWORK_STAR_SHAPE ,"item.minecraft.firework_star.shape"),
    NETHER_BRICK(Material.NETHER_BRICK, "item.minecraft.nether_brick"),
    QUARTZ(Material.QUARTZ, "item.minecraft.quartz"),
    ARMOR_STAND(Material.ARMOR_STAND, "item.minecraft.armor_stand"),
    IRON_HORSE_ARMOR(Material.IRON_HORSE_ARMOR, "item.minecraft.iron_horse_armor"),
    GOLDEN_HORSE_ARMOR(Material.GOLDEN_HORSE_ARMOR, "item.minecraft.golden_horse_armor"),
    DIAMOND_HORSE_ARMOR(Material.DIAMOND_HORSE_ARMOR, "item.minecraft.diamond_horse_armor"),
    LEATHER_HORSE_ARMOR(Material.LEATHER_HORSE_ARMOR, "item.minecraft.leather_horse_armor"),
    PRISMARINE_SHARD(Material.PRISMARINE_SHARD, "item.minecraft.prismarine_shard"),
    PRISMARINE_CRYSTALS(Material.PRISMARINE_CRYSTALS, "item.minecraft.prismarine_crystals"),
    CHORUS_FRUIT(Material.CHORUS_FRUIT, "item.minecraft.chorus_fruit"),
    POPPED_CHORUS_FRUIT(Material.POPPED_CHORUS_FRUIT, "item.minecraft.popped_chorus_fruit"),
    BEETROOT(Material.BEETROOT, "item.minecraft.beetroot"),
    BEETROOT_SEEDS(Material.BEETROOT_SEEDS, "item.minecraft.beetroot_seeds"),
    BEETROOT_SOUP(Material.BEETROOT_SOUP, "item.minecraft.beetroot_soup"),
    DRAGON_BREATH(Material.DRAGON_BREATH, "item.minecraft.dragon_breath"),
    ELYTRA(Material.ELYTRA, "item.minecraft.elytra"),
    TOTEM_OF_UNDYING(Material.TOTEM_OF_UNDYING, "item.minecraft.totem_of_undying"),
    SHULKER_SHELL(Material.SHULKER_SHELL, "item.minecraft.shulker_shell"),
    IRON_NUGGET(Material.IRON_NUGGET, "item.minecraft.iron_nugget"),
    KNOWLEDGE_BOOK(Material.KNOWLEDGE_BOOK, "item.minecraft.knowledge_book"),
    DEBUG_STICK(Material.DEBUG_STICK, "item.minecraft.debug_stick"),
    //    DEBUG_STICK_EMPTY(Material.DEBUG_STICK_EMPTY ,"item.minecraft.debug_stick.empty"),
//    DEBUG_STICK_UPDATE(Material.DEBUG_STICK_UPDATE ,"item.minecraft.debug_stick.update"),
//    DEBUG_STICK_SELECT(Material.DEBUG_STICK_SELECT ,"item.minecraft.debug_stick.select"),
    TRIDENT(Material.TRIDENT, "item.minecraft.trident"),
    SCUTE(Material.SCUTE, "item.minecraft.scute"),
    TURTLE_HELMET(Material.TURTLE_HELMET, "item.minecraft.turtle_helmet"),
    PHANTOM_MEMBRANE(Material.PHANTOM_MEMBRANE, "item.minecraft.phantom_membrane"),
    NAUTILUS_SHELL(Material.NAUTILUS_SHELL, "item.minecraft.nautilus_shell"),
    HEART_OF_THE_SEA(Material.HEART_OF_THE_SEA, "item.minecraft.heart_of_the_sea"),
    CROSSBOW(Material.CROSSBOW, "item.minecraft.crossbow"),
    //    CROSSBOW_PROJECTILE(Material.CROSSBOW_PROJECTILE ,"item.minecraft.crossbow.projectile"),
    SUSPICIOUS_STEW(Material.SUSPICIOUS_STEW, "item.minecraft.suspicious_stew"),
    CREEPER_BANNER_PATTERN(Material.CREEPER_BANNER_PATTERN, "item.minecraft.creeper_banner_pattern"),
    SKULL_BANNER_PATTERN(Material.SKULL_BANNER_PATTERN, "item.minecraft.skull_banner_pattern"),
    FLOWER_BANNER_PATTERN(Material.FLOWER_BANNER_PATTERN, "item.minecraft.flower_banner_pattern"),
    MOJANG_BANNER_PATTERN(Material.MOJANG_BANNER_PATTERN, "item.minecraft.mojang_banner_pattern"),
    GLOBE_BANNER_PATTERN(Material.GLOBE_BANNER_PATTERN, "item.minecraft.globe_banner_pattern"),
    //    CREEPER_BANNER_PATTERN_DESC(Material.CREEPER_BANNER_PATTERN_DESC ,"item.minecraft.creeper_banner_pattern.desc"),
//    SKULL_BANNER_PATTERN_DESC(Material.SKULL_BANNER_PATTERN_DESC ,"item.minecraft.skull_banner_pattern.desc"),
//    FLOWER_BANNER_PATTERN_DESC(Material.FLOWER_BANNER_PATTERN_DESC ,"item.minecraft.flower_banner_pattern.desc"),
//    MOJANG_BANNER_PATTERN_DESC(Material.MOJANG_BANNER_PATTERN_DESC ,"item.minecraft.mojang_banner_pattern.desc"),
//    GLOBE_BANNER_PATTERN_DESC(Material.GLOBE_BANNER_PATTERN_DESC ,"item.minecraft.globe_banner_pattern.desc"),
    PIGLIN_BANNER_PATTERN(Material.PIGLIN_BANNER_PATTERN, "item.minecraft.piglin_banner_pattern"),
    //    PIGLIN_BANNER_PATTERN_DESC(Material.PIGLIN_BANNER_PATTERN_DESC ,"item.minecraft.piglin_banner_pattern.desc"),
    SWEET_BERRIES(Material.SWEET_BERRIES, "item.minecraft.sweet_berries"),
    HONEY_BOTTLE(Material.HONEY_BOTTLE, "item.minecraft.honey_bottle"),
    HONEYCOMB(Material.HONEYCOMB, "item.minecraft.honeycomb"),
    //    LODESTONE_COMPASS(Material.LODESTONE_COMPASS ,"item.minecraft.lodestone_compass"),
    NETHERITE_SCRAP(Material.NETHERITE_SCRAP, "item.minecraft.netherite_scrap"),
    NETHERITE_INGOT(Material.NETHERITE_INGOT, "item.minecraft.netherite_ingot"),
    NETHERITE_HELMET(Material.NETHERITE_HELMET, "item.minecraft.netherite_helmet"),
    NETHERITE_CHESTPLATE(Material.NETHERITE_CHESTPLATE, "item.minecraft.netherite_chestplate"),
    NETHERITE_LEGGINGS(Material.NETHERITE_LEGGINGS, "item.minecraft.netherite_leggings"),
    NETHERITE_BOOTS(Material.NETHERITE_BOOTS, "item.minecraft.netherite_boots"),
    NETHERITE_AXE(Material.NETHERITE_AXE, "item.minecraft.netherite_axe"),
    NETHERITE_PICKAXE(Material.NETHERITE_PICKAXE, "item.minecraft.netherite_pickaxe"),
    NETHERITE_HOE(Material.NETHERITE_HOE, "item.minecraft.netherite_hoe"),
    NETHERITE_SHOVEL(Material.NETHERITE_SHOVEL, "item.minecraft.netherite_shovel"),
    NETHERITE_SWORD(Material.NETHERITE_SWORD, "item.minecraft.netherite_sword"),
    WARPED_FUNGUS_ON_A_STICK(Material.WARPED_FUNGUS_ON_A_STICK, "item.minecraft.warped_fungus_on_a_stick"),
    GLOW_INK_SAC(Material.GLOW_INK_SAC, "item.minecraft.glow_ink_sac"),
    GLOW_ITEM_FRAME(Material.GLOW_ITEM_FRAME, "item.minecraft.glow_item_frame"),
    TIPPED_ARROW_EFFECT_EMPTY(Material.TIPPED_ARROW, "item.minecraft.tipped_arrow.effect.empty"),
    TIPPED_ARROW_EFFECT_WATER(Material.TIPPED_ARROW_EFFECT_WATER, "item.minecraft.tipped_arrow.effect.water"),
    TIPPED_ARROW_EFFECT_MUNDANE(Material.TIPPED_ARROW_EFFECT_MUNDANE, "item.minecraft.tipped_arrow.effect.mundane"),
    TIPPED_ARROW_EFFECT_THICK(Material.TIPPED_ARROW_EFFECT_THICK, "item.minecraft.tipped_arrow.effect.thick"),
    TIPPED_ARROW_EFFECT_AWKWARD(Material.TIPPED_ARROW_EFFECT_AWKWARD, "item.minecraft.tipped_arrow.effect.awkward"),
    TIPPED_ARROW_EFFECT_NIGHT_VISION(Material.TIPPED_ARROW_EFFECT_NIGHT_VISION, "item.minecraft.tipped_arrow.effect.night_vision"),
    TIPPED_ARROW_EFFECT_INVISIBILITY(Material.TIPPED_ARROW_EFFECT_INVISIBILITY, "item.minecraft.tipped_arrow.effect.invisibility"),
    TIPPED_ARROW_EFFECT_LEAPING(Material.TIPPED_ARROW_EFFECT_LEAPING, "item.minecraft.tipped_arrow.effect.leaping"),
    TIPPED_ARROW_EFFECT_FIRE_RESISTANCE(Material.TIPPED_ARROW_EFFECT_FIRE_RESISTANCE, "item.minecraft.tipped_arrow.effect.fire_resistance"),
    TIPPED_ARROW_EFFECT_SWIFTNESS(Material.TIPPED_ARROW_EFFECT_SWIFTNESS, "item.minecraft.tipped_arrow.effect.swiftness"),
    TIPPED_ARROW_EFFECT_SLOWNESS(Material.TIPPED_ARROW_EFFECT_SLOWNESS, "item.minecraft.tipped_arrow.effect.slowness"),
    TIPPED_ARROW_EFFECT_WATER_BREATHING(Material.TIPPED_ARROW_EFFECT_WATER_BREATHING, "item.minecraft.tipped_arrow.effect.water_breathing"),
    TIPPED_ARROW_EFFECT_HEALING(Material.TIPPED_ARROW_EFFECT_HEALING, "item.minecraft.tipped_arrow.effect.healing"),
    TIPPED_ARROW_EFFECT_HARMING(Material.TIPPED_ARROW_EFFECT_HARMING, "item.minecraft.tipped_arrow.effect.harming"),
    TIPPED_ARROW_EFFECT_POISON(Material.TIPPED_ARROW_EFFECT_POISON, "item.minecraft.tipped_arrow.effect.poison"),
    TIPPED_ARROW_EFFECT_REGENERATION(Material.TIPPED_ARROW_EFFECT_REGENERATION, "item.minecraft.tipped_arrow.effect.regeneration"),
    TIPPED_ARROW_EFFECT_STRENGTH(Material.TIPPED_ARROW_EFFECT_STRENGTH, "item.minecraft.tipped_arrow.effect.strength"),
    TIPPED_ARROW_EFFECT_WEAKNESS(Material.TIPPED_ARROW_EFFECT_WEAKNESS, "item.minecraft.tipped_arrow.effect.weakness"),
    TIPPED_ARROW_EFFECT_LEVITATION(Material.TIPPED_ARROW_EFFECT_LEVITATION, "item.minecraft.tipped_arrow.effect.levitation"),
    TIPPED_ARROW_EFFECT_LUCK(Material.TIPPED_ARROW_EFFECT_LUCK, "item.minecraft.tipped_arrow.effect.luck"),
    TIPPED_ARROW_EFFECT_TURTLE_MASTER(Material.TIPPED_ARROW_EFFECT_TURTLE_MASTER, "item.minecraft.tipped_arrow.effect.turtle_master"),
    TIPPED_ARROW_EFFECT_SLOW_FALLING(Material.TIPPED_ARROW_EFFECT_SLOW_FALLING, "item.minecraft.tipped_arrow.effect.slow_falling"),
    POTION_EFFECT_EMPTY(Material.POTION_EFFECT_EMPTY, "item.minecraft.potion.effect.empty"),
    POTION_EFFECT_WATER(Material.POTION_EFFECT_WATER, "item.minecraft.potion.effect.water"),
    POTION_EFFECT_MUNDANE(Material.POTION_EFFECT_MUNDANE, "item.minecraft.potion.effect.mundane"),
    POTION_EFFECT_THICK(Material.POTION_EFFECT_THICK, "item.minecraft.potion.effect.thick"),
    POTION_EFFECT_AWKWARD(Material.POTION_EFFECT_AWKWARD, "item.minecraft.potion.effect.awkward"),
    POTION_EFFECT_NIGHT_VISION(Material.POTION_EFFECT_NIGHT_VISION, "item.minecraft.potion.effect.night_vision"),
    POTION_EFFECT_INVISIBILITY(Material.POTION_EFFECT_INVISIBILITY, "item.minecraft.potion.effect.invisibility"),
    POTION_EFFECT_LEAPING(Material.POTION_EFFECT_LEAPING, "item.minecraft.potion.effect.leaping"),
    POTION_EFFECT_FIRE_RESISTANCE(Material.POTION_EFFECT_FIRE_RESISTANCE, "item.minecraft.potion.effect.fire_resistance"),
    POTION_EFFECT_SWIFTNESS(Material.POTION_EFFECT_SWIFTNESS, "item.minecraft.potion.effect.swiftness"),
    POTION_EFFECT_SLOWNESS(Material.POTION_EFFECT_SLOWNESS, "item.minecraft.potion.effect.slowness"),
    POTION_EFFECT_WATER_BREATHING(Material.POTION_EFFECT_WATER_BREATHING, "item.minecraft.potion.effect.water_breathing"),
    POTION_EFFECT_HEALING(Material.POTION_EFFECT_HEALING, "item.minecraft.potion.effect.healing"),
    POTION_EFFECT_HARMING(Material.POTION_EFFECT_HARMING, "item.minecraft.potion.effect.harming"),
    POTION_EFFECT_POISON(Material.POTION_EFFECT_POISON, "item.minecraft.potion.effect.poison"),
    POTION_EFFECT_REGENERATION(Material.POTION_EFFECT_REGENERATION, "item.minecraft.potion.effect.regeneration"),
    POTION_EFFECT_STRENGTH(Material.POTION_EFFECT_STRENGTH, "item.minecraft.potion.effect.strength"),
    POTION_EFFECT_WEAKNESS(Material.POTION_EFFECT_WEAKNESS, "item.minecraft.potion.effect.weakness"),
    POTION_EFFECT_LEVITATION(Material.POTION_EFFECT_LEVITATION, "item.minecraft.potion.effect.levitation"),
    POTION_EFFECT_LUCK(Material.POTION_EFFECT_LUCK, "item.minecraft.potion.effect.luck"),
    POTION_EFFECT_TURTLE_MASTER(Material.POTION_EFFECT_TURTLE_MASTER, "item.minecraft.potion.effect.turtle_master"),
    POTION_EFFECT_SLOW_FALLING(Material.POTION_EFFECT_SLOW_FALLING, "item.minecraft.potion.effect.slow_falling"),
    SPLASH_POTION_EFFECT_EMPTY(Material.SPLASH_POTION_EFFECT_EMPTY, "item.minecraft.splash_potion.effect.empty"),
    SPLASH_POTION_EFFECT_WATER(Material.SPLASH_POTION_EFFECT_WATER, "item.minecraft.splash_potion.effect.water"),
    SPLASH_POTION_EFFECT_MUNDANE(Material.SPLASH_POTION_EFFECT_MUNDANE, "item.minecraft.splash_potion.effect.mundane"),
    SPLASH_POTION_EFFECT_THICK(Material.SPLASH_POTION_EFFECT_THICK, "item.minecraft.splash_potion.effect.thick"),
    SPLASH_POTION_EFFECT_AWKWARD(Material.SPLASH_POTION_EFFECT_AWKWARD, "item.minecraft.splash_potion.effect.awkward"),
    SPLASH_POTION_EFFECT_NIGHT_VISION(Material.SPLASH_POTION_EFFECT_NIGHT_VISION, "item.minecraft.splash_potion.effect.night_vision"),
    SPLASH_POTION_EFFECT_INVISIBILITY(Material.SPLASH_POTION_EFFECT_INVISIBILITY, "item.minecraft.splash_potion.effect.invisibility"),
    SPLASH_POTION_EFFECT_LEAPING(Material.SPLASH_POTION_EFFECT_LEAPING, "item.minecraft.splash_potion.effect.leaping"),
    SPLASH_POTION_EFFECT_FIRE_RESISTANCE(Material.SPLASH_POTION_EFFECT_FIRE_RESISTANCE, "item.minecraft.splash_potion.effect.fire_resistance"),
    SPLASH_POTION_EFFECT_SWIFTNESS(Material.SPLASH_POTION_EFFECT_SWIFTNESS, "item.minecraft.splash_potion.effect.swiftness"),
    SPLASH_POTION_EFFECT_SLOWNESS(Material.SPLASH_POTION_EFFECT_SLOWNESS, "item.minecraft.splash_potion.effect.slowness"),
    SPLASH_POTION_EFFECT_WATER_BREATHING(Material.SPLASH_POTION_EFFECT_WATER_BREATHING, "item.minecraft.splash_potion.effect.water_breathing"),
    SPLASH_POTION_EFFECT_HEALING(Material.SPLASH_POTION_EFFECT_HEALING, "item.minecraft.splash_potion.effect.healing"),
    SPLASH_POTION_EFFECT_HARMING(Material.SPLASH_POTION_EFFECT_HARMING, "item.minecraft.splash_potion.effect.harming"),
    SPLASH_POTION_EFFECT_POISON(Material.SPLASH_POTION_EFFECT_POISON, "item.minecraft.splash_potion.effect.poison"),
    SPLASH_POTION_EFFECT_REGENERATION(Material.SPLASH_POTION_EFFECT_REGENERATION, "item.minecraft.splash_potion.effect.regeneration"),
    SPLASH_POTION_EFFECT_STRENGTH(Material.SPLASH_POTION_EFFECT_STRENGTH, "item.minecraft.splash_potion.effect.strength"),
    SPLASH_POTION_EFFECT_WEAKNESS(Material.SPLASH_POTION_EFFECT_WEAKNESS, "item.minecraft.splash_potion.effect.weakness"),
    SPLASH_POTION_EFFECT_LEVITATION(Material.SPLASH_POTION_EFFECT_LEVITATION, "item.minecraft.splash_potion.effect.levitation"),
    SPLASH_POTION_EFFECT_LUCK(Material.SPLASH_POTION_EFFECT_LUCK, "item.minecraft.splash_potion.effect.luck"),
    SPLASH_POTION_EFFECT_TURTLE_MASTER(Material.SPLASH_POTION_EFFECT_TURTLE_MASTER, "item.minecraft.splash_potion.effect.turtle_master"),
    SPLASH_POTION_EFFECT_SLOW_FALLING(Material.SPLASH_POTION_EFFECT_SLOW_FALLING, "item.minecraft.splash_potion.effect.slow_falling"),
    LINGERING_POTION_EFFECT_EMPTY(Material.LINGERING_POTION_EFFECT_EMPTY, "item.minecraft.lingering_potion.effect.empty"),
    LINGERING_POTION_EFFECT_WATER(Material.LINGERING_POTION_EFFECT_WATER, "item.minecraft.lingering_potion.effect.water"),
    LINGERING_POTION_EFFECT_MUNDANE(Material.LINGERING_POTION_EFFECT_MUNDANE, "item.minecraft.lingering_potion.effect.mundane"),
    LINGERING_POTION_EFFECT_THICK(Material.LINGERING_POTION_EFFECT_THICK, "item.minecraft.lingering_potion.effect.thick"),
    LINGERING_POTION_EFFECT_AWKWARD(Material.LINGERING_POTION_EFFECT_AWKWARD, "item.minecraft.lingering_potion.effect.awkward"),
    LINGERING_POTION_EFFECT_NIGHT_VISION(Material.LINGERING_POTION_EFFECT_NIGHT_VISION, "item.minecraft.lingering_potion.effect.night_vision"),
    LINGERING_POTION_EFFECT_INVISIBILITY(Material.LINGERING_POTION_EFFECT_INVISIBILITY, "item.minecraft.lingering_potion.effect.invisibility"),
    LINGERING_POTION_EFFECT_LEAPING(Material.LINGERING_POTION_EFFECT_LEAPING, "item.minecraft.lingering_potion.effect.leaping"),
    LINGERING_POTION_EFFECT_FIRE_RESISTANCE(Material.LINGERING_POTION_EFFECT_FIRE_RESISTANCE, "item.minecraft.lingering_potion.effect.fire_resistance"),
    LINGERING_POTION_EFFECT_SWIFTNESS(Material.LINGERING_POTION_EFFECT_SWIFTNESS, "item.minecraft.lingering_potion.effect.swiftness"),
    LINGERING_POTION_EFFECT_SLOWNESS(Material.LINGERING_POTION_EFFECT_SLOWNESS, "item.minecraft.lingering_potion.effect.slowness"),
    LINGERING_POTION_EFFECT_WATER_BREATHING(Material.LINGERING_POTION_EFFECT_WATER_BREATHING, "item.minecraft.lingering_potion.effect.water_breathing"),
    LINGERING_POTION_EFFECT_HEALING(Material.LINGERING_POTION_EFFECT_HEALING, "item.minecraft.lingering_potion.effect.healing"),
    LINGERING_POTION_EFFECT_HARMING(Material.LINGERING_POTION_EFFECT_HARMING, "item.minecraft.lingering_potion.effect.harming"),
    LINGERING_POTION_EFFECT_POISON(Material.LINGERING_POTION_EFFECT_POISON, "item.minecraft.lingering_potion.effect.poison"),
    LINGERING_POTION_EFFECT_REGENERATION(Material.LINGERING_POTION_EFFECT_REGENERATION, "item.minecraft.lingering_potion.effect.regeneration"),
    LINGERING_POTION_EFFECT_STRENGTH(Material.LINGERING_POTION_EFFECT_STRENGTH, "item.minecraft.lingering_potion.effect.strength"),
    LINGERING_POTION_EFFECT_WEAKNESS(Material.LINGERING_POTION_EFFECT_WEAKNESS, "item.minecraft.lingering_potion.effect.weakness"),
    LINGERING_POTION_EFFECT_LEVITATION(Material.LINGERING_POTION_EFFECT_LEVITATION, "item.minecraft.lingering_potion.effect.levitation"),
    LINGERING_POTION_EFFECT_LUCK(Material.LINGERING_POTION_EFFECT_LUCK, "item.minecraft.lingering_potion.effect.luck"),
    LINGERING_POTION_EFFECT_TURTLE_MASTER(Material.LINGERING_POTION_EFFECT_TURTLE_MASTER, "item.minecraft.lingering_potion.effect.turtle_master"),
    LINGERING_POTION_EFFECT_SLOW_FALLING(Material.LINGERING_POTION_EFFECT_SLOW_FALLING, "item.minecraft.lingering_potion.effect.slow_falling"),
    SHIELD(Material.SHIELD, "item.minecraft.shield"),
    SHIELD_BLACK(Material.SHIELD, "item.minecraft.shield.black"),
    SHIELD_RED(Material.SHIELD_RED, "item.minecraft.shield.red"),
    SHIELD_GREEN(Material.SHIELD_GREEN, "item.minecraft.shield.green"),
    SHIELD_BROWN(Material.SHIELD_BROWN, "item.minecraft.shield.brown"),
    SHIELD_BLUE(Material.SHIELD_BLUE, "item.minecraft.shield.blue"),
    SHIELD_PURPLE(Material.SHIELD_PURPLE, "item.minecraft.shield.purple"),
    SHIELD_CYAN(Material.SHIELD_CYAN, "item.minecraft.shield.cyan"),
    SHIELD_LIGHT_GRAY(Material.SHIELD_LIGHT_GRAY, "item.minecraft.shield.light_gray"),
    SHIELD_GRAY(Material.SHIELD_GRAY, "item.minecraft.shield.gray"),
    SHIELD_PINK(Material.SHIELD_PINK, "item.minecraft.shield.pink"),
    SHIELD_LIME(Material.SHIELD_LIME, "item.minecraft.shield.lime"),
    SHIELD_YELLOW(Material.SHIELD_YELLOW, "item.minecraft.shield.yellow"),
    SHIELD_LIGHT_BLUE(Material.SHIELD_LIGHT_BLUE, "item.minecraft.shield.light_blue"),
    SHIELD_MAGENTA(Material.SHIELD_MAGENTA, "item.minecraft.shield.magenta"),
    SHIELD_ORANGE(Material.SHIELD_ORANGE, "item.minecraft.shield.orange"),
    SHIELD_WHITE(Material.SHIELD_WHITE, "item.minecraft.shield.white");


    private static final Map<Material, EnumItem> lookup = new HashMap<>();

    static {
        for (EnumItem item : EnumSet.allOf(EnumItem.class)) {
            try {
                lookup.put(item.getMaterial(), item);
            } catch (Exception e) {
                continue;
            }
        }
    }

    private Material material;
    private int metadata;
    private String unlocalizedName;

    EnumItem(Material material, ItemMeta itemMeta, String unlocalizedName) {
        this.material = material;
        this.metadata = metadata;
        this.unlocalizedName = unlocalizedName;
    }

    EnumItem(Material material, String unlocalizedName) {
        this(material, null, unlocalizedName);
    }

    public int getMetadata() {
        return metadata;
    }

    public Material getMaterial() {
        return material;
    }
    }

